[Metadata]
Name=jwu
Version=1
Author=Johnny Wu
Description=Light horizontal candidate theme inspired by macOS and Windows Rime themes
ScaleWithDPI=True

[InputPanel]
NormalColor=#424242
HighlightColor=#424242
HighlightBackgroundColor=#e4f0ff
HighlightCandidateColor=#006eee
CandidateLabelColor=#424242
HighlightCandidateLabelColor=#006eee
CandidateCommentColor=#999999
HighlightCandidateCommentColor=#999999
CommentTextSizeFactor=100
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=6
Right=6
Top=4
Bottom=4

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#ffffff
BorderColor=#8e8e8e
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#e4f0ff
BorderColor=#ffffff00
BorderWidth=0

[InputPanel/Highlight/Margin]
Left=4
Right=4
Top=2
Bottom=2

[Menu/Background]
Color=#ffffff
BorderColor=#8e8e8e
BorderWidth=1

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/Highlight]
Color=#e4f0ff
BorderColor=#ffffff00
BorderWidth=0

[Menu/Highlight/Margin]
Left=4
Right=4
Top=2
Bottom=2

[Menu/Separator]
Color=#d0d0d0

[Menu/TextMargin]
Left=5
Right=5
Top=4
Bottom=4

[AccentColorField]
0=Input Panel Border
1=Input Panel Highlight Candidate Background
2=Input Panel Highlight
3=Menu Border
4=Menu Separator
5=Menu Selected Item Background
